### ISSUE TITLE
blank toast message

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#728]
When I log in on the test site, a toast box pops up and it used to say something like "Successfully Logged In" but now it's just a blank box.

**Comment by lprivette** [comment]
I tested this in test and I think the text is actually there but the box itself is loading below the window, so it looks like it's empty. I did a recordit and on the third login attempt the box loaded cut-off.
![image](https://user-images.githubusercontent.com/23640741/67045510-6ea14b80-f0fc-11e9-9484-da06bba79aa0.png) https://recordit.co/UVXs188xdS

**Comment by JChipault** [comment]
it's working sporadically for me (can't figure out trend)

**Comment by JChipault** [comment]
I see bigger toast box. 
![image](https://user-images.githubusercontent.com/49287076/67050037-36e6d380-f0fd-11e9-8c97-0f7d1a17e7d2.png)

**Comment by BlakeDraper** [comment]
I think this was a minor timing thing that has been resolved. Closing for now to clean up but can be re-opened if this issue returns.

**Comment by JChipault** [comment]
happened multiple times in test 2.8.1. today. we can see if it resolves when test is pushed live (would that matter?)

**Comment by BlakeDraper** [comment]
That should not matter. This issue is a low priority for now, largely because the page immediately reloads after login anyway, but also because it is very time consuming to try to pinpoint. Are we ok with this being backburner?

**Comment by JChipault** [comment]
yup, it's fine to back burner. Just letting you know it's still happening in case you have a lightbulb moment on how to fix it.

**Comment by JChipault** [comment]
FYI - this works now.
